apiVersion: v1
kind: ConfigMap
metadata:
  name: incops-config
data:
  DB_HOST: "mysql-service"
  DB_NAME: "company_db"
  DB_USER: "root"
  REACT_APP_API_URL: "http://localhost:30001" # Minikube NodePort for Backend